### ISSUE TITLE
Docker Container Status: Exited(1)

### ISSUE THREAD

**Issue by ryanhayame** [viral-medialab/stable_diffusion_server#2]
Using docker desktop on windows 10 and running Ubuntu 20.04.5 LTS on WSL2 on Windows 10 with Gigabyte GeForce RTX 3070 GAMING OC 8G.
Followed your Readme and got up to step 5 without any issues until running "docker run -d -p 3000:3000 sd_server"
I checked what the problem was and docker desktop shows that the container is not running. This was the error:

2022-12-12 17:28:01 The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]1 
2022-12-12 17:28:02 Traceback (most recent call last):
2022-12-12 17:28:02   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-12-12 17:28:02     return _run_code(code, main_globals, None,
2022-12-12 17:28:02   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-12-12 17:28:02     exec(code, run_globals)
2022-12-12 17:28:02   File "/stable_diffusion_server/app.py", line 13, in <module>
2022-12-12 17:28:02     assert torch.cuda.is_available()
2022-12-12 17:28:02 AssertionError
2022-12-12 17:28:36 Traceback (most recent call last):
2022-12-12 17:28:36   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-12-12 17:28:36     return _run_code(code, main_globals, None,
2022-12-12 17:28:36   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-12-12 17:28:36     exec(code, run_globals)
2022-12-12 17:28:36   File "/stable_diffusion_server/app.py", line 13, in <module>
2022-12-12 17:28:36     assert torch.cuda.is_available()
2022-12-12 17:28:36 AssertionError
2022-12-12 17:28:01 Moving 0 files to the new cache system

Can you help me solve this issue? Thanks

**Comment by ryanhayame** [comment]
Is there a specific version of CUDA I should use maybe?
